# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-01-01 20:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cache', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='geocache',
            name='title',
            field=models.TextField(default='None Provided'),
        ),
    ]
