# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-01-02 13:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cache', '0002_geocache_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='geocache',
            name='description',
            field=models.TextField(default='None provided.'),
        ),
    ]
