# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-01-02 20:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cache', '0003_geocache_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='geocache',
            name='latitude',
            field=models.FloatField(default=0.0),
        ),
    ]
