# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-01-03 03:11
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cache', '0006_log'),
    ]

    operations = [
        migrations.AddField(
            model_name='log',
            name='geocache',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='cache.Geocache'),
        ),
    ]
