# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-01-08 03:20
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cache', '0008_geocache_hint'),
    ]

    operations = [
        migrations.AddField(
            model_name='geocache',
            name='difficulty',
            field=models.PositiveIntegerField(default=1, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)]),
        ),
    ]
